export const READING_PARAGRAPHS = [
  "the cat sat on the mat. the fat cat had a hat. the cat was red.",
  "a big dog ran in the sun. the dog had a ball. the dog was fun.",
  "the sun is hot. the red bus can run. the bus is big.",
  "i see a red hen. the hen is in a pen. the hen has a net.",
  "the pig is big. the pig can dig. the pig has a wig.",
  "a bug is on the rug. the bug is snug. i give the bug a hug.",
  "the lad is sad. he has a pad. the pad is bad.",
  "the jam is in the jar. the jar is in the car. the car is far.",
  "the fox is in a box. the fox has socks. the box has a lock.",
  "the wet pet is at the vet. the vet has a net. the pet is set.",
  "the man has a pan. the man has a fan. the man ran to the van.",
  "the boy has a toy. the toy is a joy. the boy is coy.",
  "the cup is up. the pup is in the cup. the pup is a top pup.",
  "the bat is on the mat. the rat is in the hat. the cat sat on the rat.",
  "the sun is up. the mud is on the rug. the pup is in the mud.",
  "the red jet is fast. the jet is in the sky. the jet is big.",
  "the ten men had a pen. the pen was red. the men sat on the bed.",
  "the fin is on the fish. the fish is in the dish. the dish is big.",
  "the pot is hot. the dot is on the pot. the pot is on the cot.",
  "the nut is in the hut. the hut is shut. the nut is cut.",
  "the gum is on the drum. the drum is fun. the gum is yum.",
  "the lid is on the bin. the bin is big. the lid is thin.",
  "the mop is on the top. the top can hop. the mop is wet.",
  "the web is on the bed. the web is red. the bug is in the web.",
  "the dad is mad. the lad is bad. the dad is sad.",
  "the log is in the bog. the dog is on the log. the dog is wet.",
  "the map is on the lap. the man has a cap. the man had a nap.",
  "the pin is in the tin. the tin is thin. the pin is sharp.",
  "the rod is for the cod. the cod is in the pod. the rod is long.",
  "the tub is in the lab. the cub is in the tub. the cub is sub.",
  "the zip is on the hip. the lip is red. the zip is fast.",
  "the bag has a tag. the rag is in the bag. the bag is big.",
  "the cob is on the job. the mob is at the bob. the cob is hot.",
  "the den is for the hen. the hen has a pen. the den is dark.",
  "the fig is on the rig. the pig is big. the fig is yum.",
  "the hop is on the top. the cop has a mop. the cop can hop.",
  "the kid has a lid. the kid hid the lid. the kid is a lad.",
  "the mad cat had a pad. the cat sat on the pad. the pad was red.",
  "the net is wet. the pet is in the net. the net is set.",
  "the owl is on the bowl. the bowl is full. the owl is big.",
  "the peg is on the leg. the leg is on the keg. the peg is red.",
  "the rib is in the bib. the bib is on the nib. the rib is thin.",
  "the sob is on the job. the rob is at the bob. the sob is sad.",
  "the tax is on the wax. the wax is on the axe. the tax is high.",
  "the urn is on the fern. the fern is in the barn. the urn is old.",
  "the vet has a pet. the pet is wet. the vet is at the net.",
  "the wig is on the pig. the pig is big. the wig is red.",
  "the yak is on the back. the back is on the sack. the yak is big.",
  "the zen is in the den. the den is for the hen. the zen is calm.",
  "the ant is on the plant. the plant is in the pot. the ant is small.",
  "the bell is in the well. the well is deep. the bell is loud.",
  "the cake is on the lake. the lake is blue. the cake is sweet.",
  "the duck is in the truck. the truck is big. the duck is yellow.",
  "the egg is in the keg. the keg is on the leg. the egg is small.",
  "the frog is on the log. the log is in the bog. the frog is green.",
  "the gift is in the lift. the lift is fast. the gift is big.",
  "the hill is by the mill. the mill is old. the hill is high.",
  "the ink is in the sink. the sink is white. the ink is blue.",
  "the jump is over the hump. the hump is big. the jump is fun.",
  "the kite is in the light. the light is bright. the kite is high.",
  "the lamp is in the camp. the camp is dark. the lamp is on.",
  "the milk is on the silk. the silk is soft. the milk is cold.",
  "the nose is on the rose. the rose is red. the nose is small.",
  "the park is in the dark. the dark is cold. the park is big.",
  "the quiz is on the whiz. the whiz is fast. the quiz is fun.",
  "the rain is on the train. the train is long. the rain is wet.",
  "the star is in the car. the car is far. the star is bright.",
  "the tent is in the vent. the vent is small. the tent is big.",
  "the unit is in the kit. the kit is small. the unit is one.",
  "the vase is on the base. the base is hard. the vase is old.",
  "the wind is in the mind. the mind is fast. the wind is cold.",
  "the x-ray is on the tray. the tray is flat. the x-ray is clear.",
  "the yard is in the card. the card is hard. the yard is big.",
  "the zone is on the bone. the bone is old. the zone is far.",
  "the apple is in the box. the box is red. the apple is sweet.",
  "the bird is in the tree. the tree is green. the bird is small.",
  "the cloud is in the sky. the sky is blue. the cloud is white.",
  "the door is on the floor. the floor is hard. the door is big.",
  "the fire is in the wire. the wire is long. the fire is hot.",
  "the gate is by the lake. the lake is deep. the gate is old.",
  "the hand is in the sand. the sand is hot. the hand is small.",
  "the ice is in the rice. the rice is white. the ice is cold.",
  "the juice is in the cup. the cup is full. the juice is sweet.",
  "the king is on the ring. the ring is gold. the king is big.",
  "the leaf is on the reef. the reef is deep. the leaf is green.",
  "the moon is in the room. the room is dark. the moon is bright.",
  "the nest is on the vest. the vest is old. the nest is small.",
  "the orange is in the box. the box is big. the orange is round.",
  "the pear is on the chair. the chair is soft. the pear is sweet.",
  "the queen is in the scene. the scene is bright. the queen is fair.",
  "the rock is in the sock. the sock is old. the rock is hard.",
  "the ship is on the trip. the trip is long. the ship is big.",
  "the tiger is in the cage. the cage is strong. the tiger is fast.",
  "the umbrella is in the rain. the rain is wet. the umbrella is blue.",
  "the vine is on the line. the line is long. the vine is green.",
  "the whale is in the gale. the gale is strong. the whale is big.",
  "the xylophone is in the home. the home is warm. the xylophone is fun.",
  "the yellow is in the mellow. the mellow is soft. the yellow is bright.",
  "the zebra is in the zoo. the zoo is big. the zebra is fast."
];
